server:
  port: 9000
#  session:
#    timeout: 30

#
spring:

  datasource:
   url: jdbc:mysql://localhost:3306/jeesite?useUnicode=true&characterEncoding=utf-8
   username: root
   password: 123123
   initial-size: 1
   min-idle: 1
   max-active: 20
   test-on-borrow: true


mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持


#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

#
#upms:
#  url: @upms.url@
#  interceptor.patterns: /**/*.do,/
#api:
#  patterns: /jenkins/list.do,/jenkins/map.do,/jenkins/get.do,/jenkins/check.do
#
## Jenkins基础信息
#jenkins:
#  url: http://oss-jenkins.eastdc.cn:85/
#  admin: admin
#  pwd: admin
#  url-part: oss-jenkins.eastdc.cn:85
#  ossPwd: keshihua123

inner-service:




